FROM php:8.2-fpm-alpine
WORKDIR /var/www/html

RUN apk add --no-cache bash \
    && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
    && apk add --no-cache libpq postgresql-dev libzip-dev icu-dev \
    && docker-php-ext-install pdo pdo_pgsql zip bcmath intl \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del .build-deps

# Usuario/grupo 'www'
RUN addgroup -g 1000 -S www && adduser -u 1000 -S www -G www

# Carpetas de Laravel (nota: si montas volúmenes, se vuelven a crear vacías en runtime)
RUN mkdir -p storage/framework/{cache,sessions,views} bootstrap/cache \
    && chown -R www:www storage bootstrap/cache

# **AQUÍ** ya que somos root, dejamos opcache apagado para dev
RUN printf "opcache.enable=0\nopcache.validate_timestamps=1\n" \
    > /usr/local/etc/php/conf.d/dev.ini

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

USER www
EXPOSE 9000
CMD ["php-fpm", "-F"]
